name: travel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+1
  path: ^1.8.3
  intl: ^0.19.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0
  sqflite_common_ffi: ^2.3.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
